<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HanumanInstitute.SynthMultiViewer.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="System.IO.Abstractions.TestingHelpers" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../SynthMultiViewer/SynthMultiViewer.csproj" />
    <ProjectReference Include="../ScriptAssist.Tests/ScriptAssist.Tests.csproj" />
  </ItemGroup>
</Project>
