<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>SynthMultiViewer</AssemblyName>
    <RootNamespace>HanumanInstitute.SynthMultiViewer</RootNamespace>
    <RuntimeIdentifiers>win-x64;win-x86;linux-x64;linux-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <ApplicationIcon>Assets/App.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <Product>Synth Multi-Viewer</Product>
    <LSApplicationCategoryType>public.app-category.developer-tools</LSApplicationCategoryType>
    <PublishSingleFile>true</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SynthMultiViewer.Tests" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets/App.ico" />
    <AvaloniaResource Include="Assets/App.webp" />
    <AvaloniaResource Include="Assets/HighlightAviSynth.xshd" />
    <AvaloniaResource Include="Assets/HighlightVapourSynth.xshd" />
    <AvaloniaResource Include="Assets/DefaultAvisynth.avs" />
    <AvaloniaResource Include="Assets/DefaultVapourSynth.vpy" />
    <AvaloniaResource Include="Assets/Icons/*.webp" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Xaml.Behaviors.Interactions.Draggable" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="ReactiveUI.SourceGenerators">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Splat" />
    <PackageReference Include="Splat.DependencyInjection.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="HanumanInstitute.Validators" />
    <PackageReference Include="System.IO.Abstractions" />
    <PackageReference Include="HanumanInstitute.MvvmDialogs" />
    <PackageReference Include="HanumanInstitute.MvvmDialogs.Avalonia" />
    <PackageReference Include="HanumanInstitute.MvvmDialogs.Avalonia.MessageBox" />
    <PackageReference Include="MediaPlayer.Avalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MediaSynthPlayer\MediaSynthPlayer.csproj" />
    <ProjectReference Include="..\ScriptAssist\ScriptAssist.csproj" />
  </ItemGroup>
</Project>
